version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/attendance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_FACEAPIURL: http://faceapi:5001
      APP_HMACSECRET: change-me
      APP_ROTATESECONDS: 20
      APP_FRONTENDHOST: http://localhost:5173
    depends_on:
      - db
    ports:
      - "8080:8080"
  faceapi:
    build:
      context: ./faceapi
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  dbdata:
